name: Bundlesize

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bundlesize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn
    - run: yarn bundlesize
      env:
        BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
